baseURL = "/"
languageCode = "fr"
title = "100 days of code"
author = "christophe ducamp"
copyright = "xtof"
googleanalytics = "UA-104942350-1"
theme ="hugo-zen"
metaDataFormat = "yaml"

[permalinks]
  post = "/:year/:month/:day/:slug/"


enableRobotsTXT = true
enableGitInfo = true
pygmentsUseClasses = true
pygmentCodeFences = true
#pygmentsStyle = "friendly"
disqusShortname = "xtof"
#googleAnalytics = "XXX"


[params]
  authorurl = "https://christopheducamp.com"
  author    = "xtof"
  logo      = "/img/logo.jpg"
  twitter   = "https://twitter.com/xtof_party"
  facebook  = "https://www.facebook.com/christophe.ducamp"
  github    = "https://github.com/ChristopheDucamp/"
  gitlab    = "https://gitlab.com/ChristopheDucamp/"
  email     = "christophe@ducamp.me"
## repo Gh pour le pied de page (inclure un slash ? la fin)
  ghrepo = "https://github.com/ChristopheDucamp/xtof-hugo-zen/"
  favicon = "img/favicon.ico"
  commit = "https://github.com/ChristopheDucamp/xtof-hugo-zen/tree"
  rss = true